inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Exclude:
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
