version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: todo_base
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - gems_cache:/gems
      - yarn_cache:/code/node_modules
      - ${PWD}/db/development.sqlite3:/code/db/development.sqlite3
      - ${PWD}/db/test.sqlite3:/code/db/test.sqlite3
    tmpfs: /code/tmp/pids
    command: "/gems/rails s -p 3000 -b 0.0.0.0"

  postgresql:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  gems_cache:
  yarn_cache:
  pgdata:
