version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUBYOPT=-W0
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - gems_home:/usr/local/bundle
      - db:/code/db
    working_dir:
      /code
    command:
      bundle exec rails s -p 3000 -b "0.0.0.0"

volumes:
  gems_home:
  db:
