version: "3"

services:
  web:
    image: docker.pkg.github.com/breckenedge/todo.breckenridge.dev/todo:latest
    environment:
      - RAILS_MASTER_KEY
      - RAILS_ENV
    ports:
      - 127.0.0.1:${HOST_PORT}:3000
    command: bin/rails s -b "0.0.0.0"
    volumes:
      sqlite: ${PWD}/production.sqlite3:/code/db/production.sqlite3
