version: "3"

services:
  web:
    image: docker.pkg.github.com/breckenedge/todo.breckenridge.dev/todo:latest
    environment:
      - POSTGRES_PASSWORD
      - RAILS_ENV
    ports:
      - 127.0.0.1:${HOST_PORT}:9292
    links:
      - postgresql
    command: bin/rails s --host "0.0.0.0"

  postgresql:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
